// ignore_for_file: avoid_print

/// Diagnostic test for conv2d divergence on PowerVR GPU.
///
/// Uses a suite of minimal conv2d models with controlled weights and
/// all-ones input to isolate exactly WHERE the Vulkan backend diverges
/// from XNNPACK on PowerVR.
///
/// Each test case has analytically known expected outputs:
///   - identity:      all values = 1.0
///   - ones_nobias:   interior = 27.0
///   - ones_bias1:    interior = 28.0
///   - pointwise:     all values = 3.0
///   - depthwise:     interior = 9.0
///   - small_weights: interior = 3.2
///   - mobilenet_real: compare Vulkan vs XNNPACK
///
/// Run on device:
///   cd example
///   flutter test integration_test/vulkan_conv_diagnostic_test.dart -d <device>

@Timeout(Duration(minutes: 10))
library;

import 'dart:convert';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:executorch_flutter/executorch_flutter.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

/// A single diagnostic test case.
class DiagCase {
  final String name;
  final String description;
  final List<int> inputShape;
  final double? expectedInterior; // null = just compare backends
  final double tolerance;

  const DiagCase({
    required this.name,
    required this.description,
    required this.inputShape,
    this.expectedInterior,
    this.tolerance = 0.01,
  });
}

const _cases = [
  DiagCase(
    name: 'identity',
    description: 'Identity weights (center tap), no bias',
    inputShape: [1, 3, 8, 8],
    expectedInterior: 1.0,
  ),
  DiagCase(
    name: 'ones_nobias',
    description: 'All-ones weights, no bias, stride=2',
    inputShape: [1, 3, 8, 8],
    expectedInterior: 27.0,
  ),
  DiagCase(
    name: 'ones_bias1',
    description: 'All-ones weights, bias=1.0, stride=2',
    inputShape: [1, 3, 8, 8],
    expectedInterior: 28.0,
  ),
  DiagCase(
    name: 'pointwise',
    description: '1x1 pointwise, ones weights',
    inputShape: [1, 3, 8, 8],
    expectedInterior: 3.0,
  ),
  DiagCase(
    name: 'depthwise',
    description: 'Depthwise 3x3, ones weights, groups=3',
    inputShape: [1, 3, 8, 8],
    expectedInterior: 9.0,
  ),
  DiagCase(
    name: 'small_weights',
    description: 'Weight=0.1, bias=0.5, stride=2',
    inputShape: [1, 3, 8, 8],
    expectedInterior: 3.2,
    tolerance: 0.05,
  ),
  DiagCase(
    name: 'mobilenet_real',
    description: 'Real MobileNet fused-BN weights (8x8 input)',
    inputShape: [1, 3, 8, 8],
  ),
  DiagCase(
    name: 'mobilenet_real_224',
    description: 'Real MobileNet fused-BN weights (224x224 input)',
    inputShape: [1, 3, 224, 224],
  ),
];

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('Conv2d Diagnostic - PowerVR', () {
    // Load expected values from JSON (generated by export script)
    Map<String, dynamic>? expectedJson;

    setUpAll(() async {
      try {
        final jsonStr = await rootBundle.loadString(
          'assets/debug_models/diag_expected.json',
        );
        expectedJson = json.decode(jsonStr) as Map<String, dynamic>;
        print('Loaded expected values from diag_expected.json');
      } catch (e) {
        print('WARNING: Could not load diag_expected.json: $e');
        print('Will use hardcoded expected values only.');
      }
    });

    for (final tc in _cases) {
      testWidgets('${tc.name}: ${tc.description}', (tester) async {
        print('\n${"=" * 70}');
        print('DIAG TEST: ${tc.name}');
        print('  ${tc.description}');
        print('  Input: ones(${tc.inputShape})');

        // Create all-ones input tensor
        final numel = tc.inputShape.reduce((a, b) => a * b);
        final floats = Float32List(numel);
        for (int i = 0; i < numel; i++) {
          floats[i] = 1.0;
        }
        final input = [
          TensorData(
            shape: tc.inputShape,
            dataType: TensorType.float32,
            data: floats.buffer.asUint8List(),
          ),
        ];

        // Get CPU reference from JSON if available
        final cpuRef = expectedJson?[tc.name] as Map<String, dynamic>?;
        if (cpuRef != null) {
          print(
            '  CPU ref: mean=${cpuRef["mean"]}, '
            'min=${cpuRef["min"]}, max=${cpuRef["max"]}',
          );
        }

        // Run XNNPACK
        final xnResult = await _runModel(
          'assets/debug_models/diag_${tc.name}_xnnpack.pte',
          input,
          'XNNPACK',
        );

        // Run Vulkan
        final vkResult = await _runModel(
          'assets/debug_models/diag_${tc.name}_vulkan.pte',
          input,
          'Vulkan',
        );

        // Validate against expected value
        if (tc.expectedInterior != null) {
          _validateExpected(xnResult, 'XNNPACK', tc.expectedInterior!, tc.tolerance);
          _validateExpected(vkResult, 'Vulkan', tc.expectedInterior!, tc.tolerance);
        }

        // Compare XNNPACK vs Vulkan
        if (xnResult != null && vkResult != null) {
          _compareOutputs(xnResult, vkResult, tc.name);
        }

        print('${"=" * 70}\n');
      });
    }

    // Summary test that runs all models and prints a comparison table
    testWidgets('SUMMARY TABLE', (tester) async {
      print('\n');
      print('=' * 90);
      print('CONV2D DIAGNOSTIC SUMMARY');
      print('=' * 90);
      print(
        '${"Model".padRight(20)} ${"Expected".padRight(10)} '
        '${"XN mean".padRight(12)} ${"VK mean".padRight(12)} '
        '${"MaxDiff".padRight(12)} ${"Status".padRight(10)}',
      );
      print('-' * 90);

      for (final tc in _cases) {
        final numel = tc.inputShape.reduce((a, b) => a * b);
        final floats = Float32List(numel);
        for (int i = 0; i < numel; i++) {
          floats[i] = 1.0;
        }
        final input = [
          TensorData(
            shape: tc.inputShape,
            dataType: TensorType.float32,
            data: floats.buffer.asUint8List(),
          ),
        ];

        final xn = await _runModelQuiet(
          'assets/debug_models/diag_${tc.name}_xnnpack.pte',
          input,
        );
        final vk = await _runModelQuiet(
          'assets/debug_models/diag_${tc.name}_vulkan.pte',
          input,
        );

        final expectedStr = tc.expectedInterior?.toStringAsFixed(1) ?? 'N/A';
        final xnMean = xn != null ? _mean(xn).toStringAsFixed(4) : 'FAIL';
        final vkMean = vk != null ? _mean(vk).toStringAsFixed(4) : 'FAIL';

        String maxDiffStr = 'N/A';
        String status = '???';

        if (xn != null && vk != null) {
          final xnFloats = xn.data.buffer.asFloat32List();
          final vkFloats = vk.data.buffer.asFloat32List();
          double maxDiff = 0;
          int nanCount = 0;
          for (int i = 0; i < math.min(xnFloats.length, vkFloats.length); i++) {
            if (vkFloats[i].isNaN || xnFloats[i].isNaN) {
              nanCount++;
              continue;
            }
            final diff = (xnFloats[i] - vkFloats[i]).abs();
            if (diff > maxDiff) maxDiff = diff;
          }
          maxDiffStr = maxDiff.toStringAsFixed(6);

          if (nanCount > 0) {
            status = 'NaN($nanCount)';
          } else if (maxDiff < 0.01) {
            status = 'MATCH';
          } else if (maxDiff < 0.1) {
            status = 'CLOSE';
          } else {
            status = 'DIVERGED';
          }
        } else if (xn == null && vk == null) {
          status = 'BOTH_FAIL';
        } else {
          status = xn == null ? 'XN_FAIL' : 'VK_FAIL';
        }

        print(
          '${tc.name.padRight(20)} ${expectedStr.padRight(10)}'
          '${xnMean.padRight(12)}'
          '${vkMean.padRight(12)}'
          '${maxDiffStr.padRight(12)}'
          '$status',
        );
      }

      print('=' * 90);
      print('');
    });
  });
}

/// Run a model and print output statistics.
Future<TensorData?> _runModel(
  String asset,
  List<TensorData> input,
  String label,
) async {
  ExecuTorchModel? model;
  try {
    try {
      model = await ExecuTorchModel.loadFromAsset(asset);
    } catch (e) {
      print('  [$label] SKIP - model not found: $e');
      return null;
    }

    final sw = Stopwatch()..start();
    final outputs = await model.forward(input);
    sw.stop();

    final output = outputs.first;
    final floats = output.data.buffer.asFloat32List();

    int nanCount = 0;
    int infCount = 0;
    double sum = 0;
    double minVal = double.infinity;
    double maxVal = double.negativeInfinity;

    for (final v in floats) {
      if (v.isNaN) {
        nanCount++;
        continue;
      }
      if (v.isInfinite) {
        infCount++;
        continue;
      }
      sum += v;
      if (v < minVal) minVal = v;
      if (v > maxVal) maxVal = v;
    }

    final validCount = floats.length - nanCount - infCount;
    final mean = validCount > 0 ? sum / validCount : 0.0;

    // Print first few values for manual inspection
    final firstN = math.min(16, floats.length);
    final firstValues =
        floats.sublist(0, firstN).map((v) => v.toStringAsFixed(4)).toList();

    String flags = '';
    if (nanCount > 0) flags += ' NaN=$nanCount';
    if (infCount > 0) flags += ' Inf=$infCount';

    print(
      '  [$label] ${sw.elapsedMilliseconds}ms | '
      'shape=${output.shape} | '
      'mean=${mean.toStringAsFixed(6)} | '
      'range=[${minVal.toStringAsFixed(4)}, ${maxVal.toStringAsFixed(4)}]$flags',
    );
    print('  [$label] first$firstN: $firstValues');

    // For Vulkan diagnostic: decode channel info from output
    // Output is NCHW. For shape [1, C, H, W], channel c is at offset c*H*W
    if (label == 'Vulkan' && output.shape.length == 4) {
      final c = output.shape[1]!;
      final h = output.shape[2]!;
      final w = output.shape[3]!;
      final spatialSize = h * w;
      // Print first spatial position (0,0) across first 4 channels
      // This corresponds to texture pos (0,0,0) channels .x,.y,.z,.w
      if (c >= 4 && spatialSize > 0) {
        final ch0 = floats[0];
        final ch1 = floats[spatialSize];
        final ch2 = floats[2 * spatialSize];
        final ch3 = floats[3 * spatialSize];
        print('  [$label] DIAG pos(0,0,0): '
            'ch0=${ch0.toStringAsFixed(4)}, '
            'ch1=${ch1.toStringAsFixed(4)}, '
            'ch2=${ch2.toStringAsFixed(4)}, '
            'ch3=${ch3.toStringAsFixed(4)}');

        // Detect which shader variant ran based on marker value:
        // 100.x = conv2d.glsl (standard sliding window)
        // 200.x = conv2d_dw.glsl (depthwise)
        // 300.x = conv2d_pw.glsl (pointwise tiled)
        // 400.x = conv2d_dw_output_tile.glsl (depthwise output tile)
        // 500.x = conv2d_dw_sned_output_tile.glsl (depthwise sned)
        // 600.x = conv2d_pw_s1p0.glsl (pointwise stride=1 pad=0)
        // 700.x = conv_transpose2d.glsl
        // No marker = diagnostic code not reached (check shader selection)
        String shaderVariant = 'unknown';
        double biasValue = ch0;
        if (ch0 >= 99.5 && ch0 < 200.0) {
          shaderVariant = 'conv2d (marker=100)';
          biasValue = ch0 - 100.0;
        } else if (ch0 >= 199.5 && ch0 < 300.0) {
          shaderVariant = 'conv2d_dw (marker=200)';
          biasValue = ch0 - 200.0;
        } else if (ch0 >= 299.5 && ch0 < 400.0) {
          shaderVariant = 'conv2d_pw (marker=300)';
          biasValue = ch0 - 300.0;
        } else if (ch0 >= 399.5 && ch0 < 500.0) {
          shaderVariant = 'conv2d_dw_output_tile (marker=400)';
          biasValue = ch0 - 400.0;
        } else if (ch0 >= 499.5 && ch0 < 600.0) {
          shaderVariant = 'conv2d_dw_sned (marker=500)';
          biasValue = ch0 - 500.0;
        } else if (ch0 >= 599.5 && ch0 < 700.0) {
          shaderVariant = 'conv2d_pw_s1p0 (marker=600)';
          biasValue = ch0 - 600.0;
        } else if (ch0 >= 699.5 && ch0 < 800.0) {
          shaderVariant = 'conv_transpose2d (marker=700)';
          biasValue = ch0 - 700.0;
        }
        print('  [$label] DIAG shader=$shaderVariant');
        print('  [$label] DIAG bias_read=${biasValue.toStringAsFixed(4)} '
            '(0.0=ZERO/BAD, non-zero=GOOD)');
      }
    }

    return output;
  } catch (e) {
    print('  [$label] ERROR: $e');
    return null;
  } finally {
    if (model != null) await model.dispose();
  }
}

/// Run a model silently (for summary table).
Future<TensorData?> _runModelQuiet(
  String asset,
  List<TensorData> input,
) async {
  ExecuTorchModel? model;
  try {
    model = await ExecuTorchModel.loadFromAsset(asset);
    final outputs = await model.forward(input);
    return outputs.first;
  } catch (_) {
    return null;
  } finally {
    if (model != null) await model.dispose();
  }
}

/// Compute mean of a tensor output.
double _mean(TensorData output) {
  final floats = output.data.buffer.asFloat32List();
  double sum = 0;
  int count = 0;
  for (final v in floats) {
    if (!v.isNaN && !v.isInfinite) {
      sum += v;
      count++;
    }
  }
  return count > 0 ? sum / count : 0.0;
}

/// Validate output against expected interior value.
void _validateExpected(
  TensorData? output,
  String label,
  double expected,
  double tolerance,
) {
  if (output == null) {
    print('  [$label] VALIDATE: SKIPPED (no output)');
    return;
  }

  final floats = output.data.buffer.asFloat32List();
  int matchCount = 0;
  int mismatchCount = 0;
  double worstDiff = 0;

  for (final v in floats) {
    if (v.isNaN) {
      mismatchCount++;
      continue;
    }
    final diff = (v - expected).abs();
    if (diff <= tolerance) {
      matchCount++;
    } else {
      mismatchCount++;
      if (diff > worstDiff) worstDiff = diff;
    }
  }

  final total = floats.length;
  final pct = (matchCount / total * 100).toStringAsFixed(1);

  if (mismatchCount == 0) {
    print('  [$label] VALIDATE: PASS (all $total values within $tolerance of $expected)');
  } else {
    print(
      '  [$label] VALIDATE: $matchCount/$total match ($pct%), '
      '$mismatchCount mismatches, worstDiff=${worstDiff.toStringAsFixed(6)}',
    );
  }
}

/// Compare XNNPACK and Vulkan outputs element-wise.
void _compareOutputs(TensorData xnOutput, TensorData vkOutput, String name) {
  final xnFloats = xnOutput.data.buffer.asFloat32List();
  final vkFloats = vkOutput.data.buffer.asFloat32List();

  if (xnFloats.length != vkFloats.length) {
    print(
      '  COMPARE: SIZE MISMATCH xnnpack=${xnFloats.length} '
      'vulkan=${vkFloats.length}',
    );
    return;
  }

  double maxDiff = 0;
  int maxDiffIdx = 0;
  int mismatchCount = 0;
  int nanCount = 0;
  double sumAbsDiff = 0;

  for (int i = 0; i < xnFloats.length; i++) {
    if (xnFloats[i].isNaN || vkFloats[i].isNaN) {
      nanCount++;
      continue;
    }
    final diff = (xnFloats[i] - vkFloats[i]).abs();
    sumAbsDiff += diff;
    if (diff > 0.01) mismatchCount++;
    if (diff > maxDiff) {
      maxDiff = diff;
      maxDiffIdx = i;
    }
  }

  final validCount = xnFloats.length - nanCount;
  final avgDiff = validCount > 0 ? sumAbsDiff / validCount : 0.0;

  print(
    '  COMPARE: maxDiff=${maxDiff.toStringAsFixed(6)} at idx=$maxDiffIdx, '
    'avgDiff=${avgDiff.toStringAsFixed(6)}, '
    'mismatches(>0.01)=$mismatchCount/$validCount, '
    'NaN=$nanCount',
  );

  if (maxDiff > 0) {
    print(
      '  COMPARE: at maxDiff idx=$maxDiffIdx: '
      'xnnpack=${xnFloats[maxDiffIdx].toStringAsFixed(6)}, '
      'vulkan=${vkFloats[maxDiffIdx].toStringAsFixed(6)}',
    );
  }

  if (nanCount > 0) {
    print('  >>> NaN DETECTED in comparison <<<');
  } else if (maxDiff < 0.01) {
    print('  >>> MATCH (maxDiff < 0.01) <<<');
  } else if (maxDiff < 0.1) {
    print('  >>> CLOSE (0.01 < maxDiff < 0.1) <<<');
  } else {
    print('  >>> DIVERGED (maxDiff >= 0.1) <<<');
  }
}
