{
  "format_version": 1,
  "sksl": {
    "entrypoint": "mobilenet_preprocess_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uInputSize;\nuniform vec2 uOutputSize;\nuniform shader uTexture;\nuniform half2 uTexture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    float scale = max(256.0 / uInputSize.x, 256.0 / uInputSize.y);\n    vec2 scaledSize = uInputSize * scale;\n    vec2 cropOffset = (scaledSize - uOutputSize) * 0.5;\n    vec2 scaledCoord = fragCoord + cropOffset;\n    vec2 inputCoord = scaledCoord / vec2(scale);\n    vec2 uv = inputCoord / uInputSize;\n    bool _67 = uv.x < 0.0;\n    bool _75;\n    if (!_67)\n    {\n        _75 = uv.x > 1.0;\n    }\n    else\n    {\n        _75 = _67;\n    }\n    bool _82;\n    if (!_75)\n    {\n        _82 = uv.y < 0.0;\n    }\n    else\n    {\n        _82 = _75;\n    }\n    bool _89;\n    if (!_82)\n    {\n        _89 = uv.y > 1.0;\n    }\n    else\n    {\n        _89 = _82;\n    }\n    if (_89)\n    {\n        fragColor = vec4(0.0, 0.0, 0.0, 1.0);\n    }\n    else\n    {\n        vec4 color = uTexture.eval(uTexture_size * ( uv));\n        vec3 normalized = (color.xyz - vec3(0.48500001430511474609375, 0.4560000002384185791015625, 0.4059999883174896240234375)) / vec3(0.2290000021457672119140625, 0.2240000069141387939453125, 0.2249999940395355224609375);\n        fragColor = vec4(normalized, 1.0);\n    }\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uInputSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uOutputSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}