{
  "sksl": {
    "entrypoint": "movenet_preprocess_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uInputSize;\nuniform vec2 uOutputSize;\nuniform shader uTexture;\nuniform half2 uTexture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv = fragCoord / uOutputSize;\n    bool _36 = uv.x < 0.0;\n    bool _44;\n    if (!_36)\n    {\n        _44 = uv.x > 1.0;\n    }\n    else\n    {\n        _44 = _36;\n    }\n    bool _52;\n    if (!_44)\n    {\n        _52 = uv.y < 0.0;\n    }\n    else\n    {\n        _52 = _44;\n    }\n    bool _59;\n    if (!_52)\n    {\n        _59 = uv.y > 1.0;\n    }\n    else\n    {\n        _59 = _52;\n    }\n    if (_59)\n    {\n        fragColor = vec4(0.0, 0.0, 0.0, 1.0);\n    }\n    else\n    {\n        vec4 color = uTexture.eval(uTexture_size * ( uv));\n        fragColor = color;\n    }\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uInputSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uOutputSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}