{
  "sksl": {
    "entrypoint": "yolo_preprocess_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uInputSize;\nuniform vec2 uOutputSize;\nuniform shader uTexture;\nuniform half2 uTexture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    float scale = min(uOutputSize.x / uInputSize.x, uOutputSize.y / uInputSize.y);\n    vec2 scaledSize = uInputSize * scale;\n    vec2 offset = (uOutputSize - scaledSize) * 0.5;\n    vec2 imageCoord = (fragCoord - offset) / vec2(scale);\n    vec2 uv = imageCoord / uInputSize;\n    bool _68 = uv.x < 0.0;\n    bool _76;\n    if (!_68)\n    {\n        _76 = uv.x > 1.0;\n    }\n    else\n    {\n        _76 = _68;\n    }\n    bool _83;\n    if (!_76)\n    {\n        _83 = uv.y < 0.0;\n    }\n    else\n    {\n        _83 = _76;\n    }\n    bool _90;\n    if (!_83)\n    {\n        _90 = uv.y > 1.0;\n    }\n    else\n    {\n        _90 = _83;\n    }\n    if (_90)\n    {\n        fragColor = vec4(0.4470588266849517822265625, 0.4470588266849517822265625, 0.4470588266849517822265625, 1.0);\n    }\n    else\n    {\n        vec4 color = uTexture.eval(uTexture_size * ( uv));\n        fragColor = color;\n    }\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uInputSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uOutputSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}